#!/usr/bin/env bash
# install-toolchain.sh — install Erlang/OTP, Elixir, Hex, and rebar3 in a fresh
# Linux sandbox without using the OS package manager.
#
# Idempotent: safe to re-run. Existing installs are skipped.
#
# Versions are pinned from the project's .tool-versions:
#   erlang 27.2
#   elixir 1.18.1-otp-27
#
# Sources (verified, no --insecure / --unsafe flags):
#   - OTP precompiled binaries:  https://builds.hex.pm/builds/otp/<distro>/
#     (the same source used by the erlef/setup-beam GitHub Action)
#   - Elixir precompiled zip:    https://github.com/elixir-lang/elixir/releases
#   - Hex archive:               https://builds.hex.pm/installs/<elixir>/hex.ez
#   - rebar3 binary:             https://github.com/erlang/rebar3/releases/latest
#
# Why this exists:
#   The Anthropic sandbox MITMs all outbound TLS via an "egress-gateway-ca".
#   Curl negotiates a fingerprint the proxy accepts, so direct downloads work.
#   But Erlang's :httpc gets 502/503 from the proxy on EVERY https host —
#   confirmed against hex.pm, jsdelivr, github.com, google.com — so Mix's
#   built-in fetcher (mix local.hex / mix local.rebar / mix deps.get) cannot
#   reach the network from inside the sandbox.
#
#   This script bootstraps everything via curl, which DOES work, then drops
#   the Hex archive and rebar3 binary into the locations Mix expects. After
#   it runs you have working `mix compile` / `mix format` / `mix test`
#   IF deps are already on disk.
#
#   `mix deps.get` itself remains blocked. See scripts/install-toolchain.sh
#   companion docs in .claude/skills/tau-toolchain/SKILL.md for the
#   sandboxed-deps workaround (push to CI, or fetch via curl + git).
#
# Usage:
#   sudo bash scripts/install-toolchain.sh        # installs to /opt/erlang & /opt/elixir
#   PREFIX=/opt bash scripts/install-toolchain.sh # override install root

set -euo pipefail

PREFIX="${PREFIX:-/opt}"
ERLANG_VERSION="${ERLANG_VERSION:-27.2}"
ELIXIR_VERSION="${ELIXIR_VERSION:-1.18.1}"
ELIXIR_OTP_MAJOR="${ELIXIR_OTP_MAJOR:-27}"

ERLANG_HOME="$PREFIX/erlang/OTP-$ERLANG_VERSION"
ELIXIR_HOME="$PREFIX/elixir"
PROFILE_FILE="${PROFILE_FILE:-/etc/profile.d/elixir.sh}"

log()  { printf '\033[1;32m[install-toolchain]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[install-toolchain]\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31m[install-toolchain]\033[0m %s\n' "$*" >&2; exit 1; }

# --- Preflight ---------------------------------------------------------------

[[ "$(uname -s)" == "Linux" ]]   || die "Linux only (got $(uname -s))."
[[ "$(uname -m)" == "x86_64" ]]  || die "x86_64 only (got $(uname -m))."

. /etc/os-release 2>/dev/null || die "Cannot read /etc/os-release."
case "$VERSION_ID" in
  24.04) DISTRO="ubuntu-24.04" ;;
  22.04) DISTRO="ubuntu-22.04" ;;
  20.04) DISTRO="ubuntu-20.04" ;;
  *) die "Unsupported distro $ID-$VERSION_ID. Add to install-toolchain.sh." ;;
esac

for tool in curl unzip tar; do
  command -v "$tool" >/dev/null || die "Missing required tool: $tool"
done

# --- Erlang ------------------------------------------------------------------

if [[ -x "$ERLANG_HOME/bin/erl" ]] && \
   "$ERLANG_HOME/bin/erl" -noshell -eval 'halt(0).' 2>/dev/null; then
  log "Erlang/OTP $ERLANG_VERSION already installed at $ERLANG_HOME — skipping."
else
  log "Downloading OTP-$ERLANG_VERSION precompiled for $DISTRO ..."
  mkdir -p "$PREFIX/erlang"
  TMP="$(mktemp -d)"
  trap 'rm -rf "$TMP"' EXIT
  curl -fsSL -o "$TMP/otp.tar.gz" \
    "https://builds.hex.pm/builds/otp/$DISTRO/OTP-$ERLANG_VERSION.tar.gz"
  tar -xzf "$TMP/otp.tar.gz" -C "$PREFIX/erlang"
  log "Running OTP Install in $ERLANG_HOME ..."
  ( cd "$ERLANG_HOME" && ./Install -minimal "$ERLANG_HOME" )
  trap - EXIT
  rm -rf "$TMP"
  "$ERLANG_HOME/bin/erl" -version
fi

# --- Elixir ------------------------------------------------------------------

if [[ -x "$ELIXIR_HOME/bin/elixir" ]] && \
   PATH="$ERLANG_HOME/bin:$ELIXIR_HOME/bin:$PATH" \
   "$ELIXIR_HOME/bin/elixir" --version 2>/dev/null \
     | grep -q "Elixir $ELIXIR_VERSION"; then
  log "Elixir $ELIXIR_VERSION already installed at $ELIXIR_HOME — skipping."
else
  log "Downloading Elixir $ELIXIR_VERSION (otp-$ELIXIR_OTP_MAJOR build) ..."
  mkdir -p "$ELIXIR_HOME"
  TMP="$(mktemp -d)"
  trap 'rm -rf "$TMP"' EXIT
  curl -fsSL -o "$TMP/elixir.zip" \
    "https://github.com/elixir-lang/elixir/releases/download/v$ELIXIR_VERSION/elixir-otp-$ELIXIR_OTP_MAJOR.zip"
  ( cd "$ELIXIR_HOME" && unzip -qo "$TMP/elixir.zip" )
  trap - EXIT
  rm -rf "$TMP"
fi

# --- Profile -----------------------------------------------------------------

log "Writing $PROFILE_FILE ..."
cat > "$PROFILE_FILE" <<EOF
# Generated by scripts/install-toolchain.sh
export ERLANG_HOME="$ERLANG_HOME"
export ELIXIR_HOME="$ELIXIR_HOME"
export PATH="\$ERLANG_HOME/bin:\$ELIXIR_HOME/bin:\$PATH"
export ELIXIR_ERL_OPTIONS="+fnu"
export LANG="\${LANG:-C.UTF-8}"
export LC_ALL="\${LC_ALL:-C.UTF-8}"
# Hex respects this for its own HTTPS verification when it can talk to Hex —
# in this sandbox the egress proxy blocks Erlang TLS regardless, but the var
# is still correct for non-sandboxed environments.
export HEX_CACERTS_PATH="/etc/ssl/certs/ca-certificates.crt"
EOF
chmod +x "$PROFILE_FILE"

# Re-source for the current shell.
# shellcheck disable=SC1090
. "$PROFILE_FILE"

elixir --version | tail -2
mix --version    | tail -1

# --- Hex archive -------------------------------------------------------------
#
# `mix local.hex --force` would normally fetch this, but Erlang's :httpc is
# blocked in the sandbox. Download via curl and install the archive offline.

ELIXIR_MINOR="$(echo "$ELIXIR_VERSION" | awk -F. '{print $1"."$2".0"}')"
HEX_EZ="$(mktemp --suffix=.ez)"

if mix hex.info >/dev/null 2>&1; then
  log "Hex archive already installed — skipping."
else
  log "Downloading Hex archive for Elixir $ELIXIR_MINOR ..."
  curl -fsSL -o "$HEX_EZ" \
    "https://builds.hex.pm/installs/$ELIXIR_MINOR/hex.ez"
  mix archive.install "$HEX_EZ" --force
  rm -f "$HEX_EZ"
fi

# --- rebar3 ------------------------------------------------------------------

REBAR3="${REBAR3:-$HOME/.mix/rebar3}"
if [[ -x "$REBAR3" ]] && "$REBAR3" --version >/dev/null 2>&1; then
  log "rebar3 already installed at $REBAR3 — skipping."
else
  log "Downloading rebar3 from GitHub release ..."
  mkdir -p "$(dirname "$REBAR3")"
  curl -fsSL -o "$REBAR3" \
    "https://github.com/erlang/rebar3/releases/latest/download/rebar3"
  chmod +x "$REBAR3"
  "$REBAR3" --version
fi

# --- Final summary -----------------------------------------------------------

log "Done. Open a new shell or 'source $PROFILE_FILE' to pick up PATH."
log ""
log "What works in the sandbox:"
log "  • mix compile / mix format / mix credo / mix test  (after deps are on disk)"
log "  • iex -S mix"
log ""
log "What does NOT work in the sandbox:"
log "  • mix deps.get  — Erlang :httpc is blocked by the egress proxy."
log "    See .claude/skills/tau-toolchain/SKILL.md for the deps workaround."
