defmodule Tau.Factory.CodingAgentShim do
  @moduledoc """
  Writes the CodingAgent shim executable (D-364..D-367, SPEC-FACTORY-FLEET §4 B4-A1).

  The shim is an `agent_bin`-shaped executable the Worker `Port.open`s exactly
  as it would the canned dogfood script. Inside its own BEAM (spawned via the
  `elixir` CLI) the shim drives `Tau.CodingAgent` (e.g. `Tau.CodingAgents.Replay`
  or `Tau.CodingAgents.ClaudeCode`), owns the branch+commit step, and emits
  D-326 `{:packet,4}` `work_ready` / `heartbeat` frames before exiting.

  ## Bridge contract (D-364..D-367)

  - **D-364** — `%Done{exit_status: 0}` over a non-empty diff → `git add -A`,
    commit, emit `work_ready{branch, real head_sha}`, exit 0.
    Empty diff → exit 0, no `work_ready` (Worker's D-326 maps to `:no_work_product`).
    Non-zero / `%Error{recoverable: false}` → exit non-zero, no `work_ready`.

  - **D-365** — `task.workspace` is set to the worker's `ws` (current dir);
    `Tau.CodingAgent.Workspace.Cwd` backend is always selected; sub-subprocess
    inherits the full environment (including `XDG_*` namespace vars).

  - **D-366** — emits `{"type":"heartbeat"}` `{:packet,4}` frames derived from
    consumed stream events (`AssistantText`, `ToolUse`, `ToolResult`, `FileEdit`),
    rate-limited to one per `heartbeat_interval_ms`. No self-clock timer.

  - **D-367** — a dispatcher/adapter crash surfaces in-stream as
    `%Error{recoverable: false}` / `%Done{exit_status: -1}`; the shim exits
    non-zero promptly (no silent hang). No `try/rescue` across process boundaries.

  ## Usage

      shim_bin = Tau.Factory.CodingAgentShim.write(dest_path,
        adapter: Tau.CodingAgents.Replay,
        replay_fixture: [...],   # or replay_fixture_phases: [{events, delay_ms}]
        branch: "feat/agent-work"
      )
  """

  @doc """
  Write the shim executable to `dest_path` and return `dest_path`.

  The shim is a shell script that invokes `elixir` with the current project's
  compiled code paths, decodes the baked-in configuration, and calls
  `Tau.Factory.CodingAgentShim.Runner.main/1`.

  Required opts:
    - `:branch` — the git branch to commit to on a successful `%Done{0}`.

  Optional opts:
    - `:adapter`               — module (default: `Tau.CodingAgents.Replay`).
    - `:replay_fixture`        — list of `%Tau.CodingAgent.Event{}` for Replay.
    - `:replay_fixture_phases` — list of `{events, delay_ms}` for phased replay.
    - `:gap_before_phase_ms`   — list of gap delays before each phase (default: [0, 0, …]).
    - `:replay_delay_ms`       — inter-event delay ms for single-fixture replay.
    - `:heartbeat_interval_ms` — ms between heartbeat frame emissions (default: nil = every event).
    - `:inspect_env_file`      — when set, the shim writes its effective env vars to this path.

  Note: `:workspace_backend` is intentionally absent. The shim always sets
  `task.workspace = ws` (the worker's cwd) directly, which IS the
  `Tau.CodingAgent.Workspace.Cwd` passthrough — the adapter API does not
  accept a backend module. Callers need not pass this option.
  """
  @spec write(String.t(), keyword()) :: String.t()
  def write(dest_path, opts \\ []) do
    config = %{
      adapter: Keyword.get(opts, :adapter, Tau.CodingAgents.Replay),
      branch: Keyword.fetch!(opts, :branch),
      replay_fixture: Keyword.get(opts, :replay_fixture),
      replay_fixture_phases: Keyword.get(opts, :replay_fixture_phases),
      gap_before_phase_ms: Keyword.get(opts, :gap_before_phase_ms),
      replay_delay_ms: Keyword.get(opts, :replay_delay_ms, 0),
      heartbeat_interval_ms: Keyword.get(opts, :heartbeat_interval_ms),
      inspect_env_file: Keyword.get(opts, :inspect_env_file),
      skip_permissions: Keyword.get(opts, :skip_permissions, false)
    }

    encoded_config =
      config
      |> :erlang.term_to_binary()
      |> Base.encode64(padding: false)

    code_paths =
      :code.get_path()
      |> Enum.map(&to_string/1)
      |> Enum.filter(&String.contains?(&1, "_build"))
      |> Enum.uniq()

    pa_args = Enum.map_join(code_paths, " ", fn p -> "-pa '#{p}'" end)

    script = """
    #!/bin/sh
    # Tau CodingAgent Shim (D-364..D-367, SPEC-FACTORY-FLEET §4 B4-A1)
    # Generated by Tau.Factory.CodingAgentShim.write/2
    exec elixir #{pa_args} -e "
    encoded = \\"#{encoded_config}\\"
    config = :erlang.binary_to_term(Base.decode64!(encoded, padding: false))
    Tau.Factory.CodingAgentShim.Runner.main(config)
    "
    """

    File.write!(dest_path, script)
    File.chmod!(dest_path, 0o755)
    dest_path
  end
end

defmodule Tau.Factory.CodingAgentShim.Runner do
  @moduledoc """
  Entry point called by the generated shim executable.

  Runs inside a `elixir` subprocess spawned by the Worker's Port. Drives the
  configured CodingAgent adapter, emits `{:packet,4}` heartbeat frames from
  stream events, performs the branch+commit step on success, and emits a
  `work_ready` frame before exiting 0. Exits non-zero on failure or empty diff.

  All stdout output is `{:packet,4}` framing only (diagnostics go to stderr
  — mirrors the dogfood script's stderr discipline).
  """

  alias Tau.CodingAgent.Event

  # Heartbeat-triggering event types (D-366).
  @heartbeat_event_types [
    Event.AssistantText,
    Event.ToolUse,
    Event.ToolResult,
    Event.FileEdit
  ]

  @doc """
  Main entry point called from the generated shim script.
  """
  @spec main(map()) :: no_return()
  def main(config) do
    # Application.ensure_all_started is not needed — Jason and Tau modules
    # are available via code path; no supervision tree needed for Replay.
    # Ensure Jason is loaded for JSON encoding.
    {:ok, _} = Application.ensure_all_started(:jason)

    ws = File.cwd!()

    # D-365: write inspect_env_file if requested (isolation test probe).
    write_inspect_env_file(ws, config[:inspect_env_file])

    # Set up git config for commits (mirrors dogfood agent pattern).
    System.cmd("git", ["config", "user.email", "shim@tau.factory"],
      cd: ws,
      stderr_to_stdout: true
    )

    System.cmd("git", ["config", "user.name", "Tau CodingAgent Shim"],
      cd: ws,
      stderr_to_stdout: true
    )

    # Run the adapter stream and process events.
    result = run_stream(ws, config)

    case result do
      {:done, exit_status} when exit_status == 0 ->
        # Check for non-empty diff.
        case git_diff_stat(ws) do
          :non_empty ->
            branch = config.branch

            # git add -A + commit the agent's diff.
            {_out, 0} =
              System.cmd("git", ["checkout", "-B", branch],
                cd: ws,
                stderr_to_stdout: true
              )

            {_out, 0} =
              System.cmd("git", ["add", "-A"], cd: ws, stderr_to_stdout: true)

            {_out, 0} =
              System.cmd(
                "git",
                ["commit", "-m", "agent work product (CodingAgent shim, D-364)"],
                cd: ws,
                stderr_to_stdout: true
              )

            head_sha = git_rev_parse(ws, "HEAD")
            emit_work_ready(branch, head_sha)
            System.halt(0)

          :empty ->
            # Empty diff — no work_ready; exit 0 so Worker maps to :no_work_product.
            System.halt(0)
        end

      {:done, _non_zero} ->
        # Non-zero exit — emit no work_ready; exit non-zero for retry ladder.
        System.halt(1)

      {:error, _reason} ->
        System.halt(1)
    end
  end

  # ---------------------------------------------------------------------------
  # Stream execution
  # ---------------------------------------------------------------------------

  # Run the adapter stream (single fixture or phased), processing events and
  # emitting heartbeat frames. Returns {:done, exit_status} or {:error, reason}.
  defp run_stream(ws, config) do
    hb_interval = config[:heartbeat_interval_ms]

    # Initial heartbeat state: last_hb_at = nil (no heartbeat sent yet).
    initial_hb_state = %{last_hb_at: nil, interval_ms: hb_interval}

    skip_permissions = config[:skip_permissions] || false

    case resolve_stream_mode(config) do
      {:single, fixture, delay_ms} ->
        run_single_stream(ws, config.adapter, fixture, delay_ms, initial_hb_state, skip_permissions)

      {:phased, phases, gaps} ->
        run_phased_stream(ws, config.adapter, phases, gaps, initial_hb_state)
    end
  end

  defp resolve_stream_mode(%{replay_fixture_phases: phases} = config)
       when is_list(phases) and phases != [] do
    gaps = config[:gap_before_phase_ms] || List.duplicate(0, length(phases))
    {:phased, phases, gaps}
  end

  defp resolve_stream_mode(%{replay_fixture: fixture} = config) when is_list(fixture) do
    {:single, fixture, config[:replay_delay_ms] || 0}
  end

  defp resolve_stream_mode(config) do
    # No fixture — use a default empty fixture (should not happen in practice).
    {:single, [], config[:replay_delay_ms] || 0}
  end

  defp run_single_stream(ws, adapter, fixture, delay_ms, hb_state, skip_permissions) do
    # D-381: read the brief from the Worker-injected TAU_AGENT_PROMPT env var.
    # Falls back to "" when absent (back-compat with Replay / non-D-381 paths).
    task = %{
      prompt: System.get_env("TAU_AGENT_PROMPT") || "",
      workspace: ws,
      replay_fixture: fixture,
      skip_permissions: skip_permissions
    }

    ctx = if delay_ms > 0, do: %{replay_delay_ms: delay_ms}, else: %{}

    case adapter.start(task, ctx) do
      {:ok, stream} ->
        drain_stream(ws, stream, hb_state)

      {:error, reason} ->
        {:error, reason}
    end
  end

  defp run_phased_stream(ws, adapter, phases, gaps, hb_state) do
    Enum.zip(phases, gaps)
    |> Enum.reduce_while({:continue, hb_state}, fn {{events, delay_ms}, gap_ms},
                                                   {:continue, hb_st} ->
      # Wait the gap before this phase's events arrive.
      if gap_ms > 0, do: Process.sleep(gap_ms)

      # The events in this phase may or may not include a terminal Done.
      # D-381: read the brief from the Worker-injected TAU_AGENT_PROMPT env var.
      task = %{
        prompt: System.get_env("TAU_AGENT_PROMPT") || "",
        workspace: ws,
        replay_fixture: events
      }

      ctx = if delay_ms > 0, do: %{replay_delay_ms: delay_ms}, else: %{}

      case adapter.start(task, ctx) do
        {:ok, stream} ->
          case drain_stream_partial(ws, stream, hb_st) do
            {:done, _exit_status} = terminal ->
              {:halt, terminal}

            {:error, _} = err ->
              {:halt, err}

            {:continue, new_hb_st} ->
              {:cont, {:continue, new_hb_st}}
          end

        {:error, reason} ->
          {:halt, {:error, reason}}
      end
    end)
    |> case do
      {:done, _} = result -> result
      {:error, _} = result -> result
      # If we exhaust all phases without a Done, treat as error.
      {:continue, _} -> {:error, :stream_exhausted_without_done}
    end
  end

  # Drain a stream to completion, emitting heartbeats on progress events and
  # materializing any FileEdit events (so the Replay adapter's file-edit
  # events produce a real diff in the worktree — D-364).
  # Returns {:done, exit_status} or {:error, reason}.
  defp drain_stream(ws, stream, hb_state) do
    Enum.reduce_while(stream, {:ok, hb_state}, fn event, {:ok, hb_st} ->
      materialize_file_edit(ws, event)
      new_hb_st = maybe_emit_heartbeat(event, hb_st)

      case event do
        %Event.Done{exit_status: status} ->
          {:halt, {:done, status}}

        %Event.Error{recoverable: false} ->
          {:halt, {:error, event.reason}}

        _ ->
          {:cont, {:ok, new_hb_st}}
      end
    end)
    |> case do
      {:done, _} = r -> r
      {:error, _} = r -> r
      {:ok, _} -> {:error, :stream_exhausted_without_done}
    end
  end

  # Drain a stream that may or may not have a Done event (for phased execution).
  # Returns {:done, exit_status}, {:error, reason}, or {:continue, hb_state}.
  defp drain_stream_partial(ws, stream, hb_state) do
    Enum.reduce_while(stream, {:continue, hb_state}, fn event, {:continue, hb_st} ->
      materialize_file_edit(ws, event)
      new_hb_st = maybe_emit_heartbeat(event, hb_st)

      case event do
        %Event.Done{exit_status: status} ->
          {:halt, {:done, status}}

        %Event.Error{recoverable: false} ->
          {:halt, {:error, event.reason}}

        _ ->
          {:cont, {:continue, new_hb_st}}
      end
    end)
  end

  # Materialize a FileEdit event into the worktree so the Replay adapter's
  # declared edits produce a real diff (D-364). For real adapters (ClaudeCode),
  # the files are already edited by the subprocess; this is a Replay-only step.
  defp materialize_file_edit(ws, %Event.FileEdit{path: path, kind: kind}) do
    # Resolve relative paths against the worktree root.
    abs_path =
      if Path.type(path) == :absolute do
        path
      else
        Path.join(ws, path)
      end

    case kind do
      :create ->
        File.mkdir_p!(Path.dirname(abs_path))
        # Write a placeholder file (real content comes from the adapter).
        unless File.exists?(abs_path) do
          File.write!(abs_path, "# generated by CodingAgent shim (replay)\n")
        end

      :modify ->
        if File.exists?(abs_path) do
          File.write!(abs_path, File.read!(abs_path) <> "# modified by shim\n")
        end

      :delete ->
        File.rm(abs_path)
    end
  end

  defp materialize_file_edit(_ws, _event), do: :ok

  # ---------------------------------------------------------------------------
  # Heartbeat emission (D-366)
  # ---------------------------------------------------------------------------

  # Emit a heartbeat frame if the event is a progress event AND the rate-limit
  # window has elapsed since the last heartbeat.
  defp maybe_emit_heartbeat(event, hb_state) do
    if heartbeat_event?(event) do
      now = System.monotonic_time(:millisecond)
      interval = hb_state.interval_ms

      should_emit =
        cond do
          is_nil(interval) ->
            # No rate-limit: emit on every progress event.
            true

          is_nil(hb_state.last_hb_at) ->
            # First heartbeat.
            true

          now - hb_state.last_hb_at >= interval ->
            true

          true ->
            false
        end

      if should_emit do
        emit_heartbeat()
        %{hb_state | last_hb_at: now}
      else
        hb_state
      end
    else
      hb_state
    end
  end

  defp heartbeat_event?(%mod{}) when mod in @heartbeat_event_types, do: true
  defp heartbeat_event?(_), do: false

  # ---------------------------------------------------------------------------
  # {packet,4} frame emission
  # ---------------------------------------------------------------------------

  defp emit_heartbeat do
    payload = ~s({"type":"heartbeat"})
    write_packet(payload)
  end

  defp emit_work_ready(branch, head_sha) do
    payload = Jason.encode!(%{type: "work_ready", branch: branch, head_sha: head_sha})
    write_packet(payload)
  end

  # Write a {packet,4} frame to stdout. The frame is a 4-byte big-endian
  # unsigned integer length prefix followed by the payload bytes. This is the
  # wire format the Worker's Port (opened with {:packet, 4}) expects.
  defp write_packet(payload) when is_binary(payload) do
    len = byte_size(payload)
    frame = <<len::unsigned-big-integer-size(32)>> <> payload
    IO.binwrite(:stdio, frame)
  end

  # ---------------------------------------------------------------------------
  # Git helpers
  # ---------------------------------------------------------------------------

  defp git_diff_stat(ws) do
    case System.cmd("git", ["status", "--porcelain"], cd: ws, stderr_to_stdout: true) do
      {"", 0} -> :empty
      {_out, 0} -> :non_empty
      _ -> :empty
    end
  end

  defp git_rev_parse(ws, ref) do
    case System.cmd("git", ["rev-parse", ref], cd: ws, stderr_to_stdout: true) do
      {out, 0} -> String.trim(out)
      _ -> ""
    end
  end

  # ---------------------------------------------------------------------------
  # D-365: env inspection
  # ---------------------------------------------------------------------------

  defp write_inspect_env_file(_ws, nil), do: :ok

  defp write_inspect_env_file(ws, path) do
    keys = ["XDG_DATA_HOME", "MIX_HOME", "HEX_HOME"]

    lines =
      Enum.flat_map(keys, fn k ->
        case System.get_env(k) do
          nil -> []
          v -> ["#{k}=#{v}"]
        end
      end)

    # Also write the effective workspace so the test can verify ws-relativity.
    ws_line = "WORKSPACE=#{ws}"
    content = Enum.join([ws_line | lines], "\n") <> "\n"

    File.write!(path, content)
    :ok
  end
end
